### ISSUE TITLE
Problem on android(run perfectly fine in IOS)

### ISSUE THREAD

**Issue by wichayutdew** [jogboms/flutter_offline#30]
After I've implement your package, the IOS application works perfectly but on the android it always throwing Missing plugin Exception

This is what happened on
![Screenshot_1586096896](https://user-images.githubusercontent.com/34377409/78501085-5ee9f200-7784-11ea-898b-109f4a4a2357.png)

**Device log**

```
I/flutter ( 5730): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5730): The following OfflineBuilderError was thrown building StreamBuilder<ConnectivityResult>(dirty,
I/flutter ( 5730): state: _StreamBuilderBaseState<ConnectivityResult, AsyncSnapshot<ConnectivityResult>>#e2477):
I/flutter ( 5730): MissingPluginException(No implementation found for method check on channel
I/flutter ( 5730): plugins.flutter.io/connectivity)
I/flutter ( 5730): 
I/flutter ( 5730): The relevant error-causing widget was:
I/flutter ( 5730):   StreamBuilder<ConnectivityResult>
I/flutter ( 5730):   file:///Users/wichayut/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_offline-0.3.0/lib/src/main.dart:81:12
I/flutter ( 5730): 
I/flutter ( 5730): When the exception was thrown, this was the stack:
I/flutter ( 5730): #0      OfflineBuilderState.build.<anonymous closure> (package:flutter_offline/src/main.dart:92:11)
I/flutter ( 5730): #1      StreamBuilder.build (package:flutter/src/widgets/async.dart:509:81)
I/flutter ( 5730): #2      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:127:48)
I/flutter ( 5730): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
I/flutter ( 5730): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter ( 5730): #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter ( 5730): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter ( 5730): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter ( 5730): #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:864:20)
I/flutter ( 5730): #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter ( 5730): #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter ( 5730): #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter ( 5730): #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter ( 5730): #16     _invoke (dart:ui/hooks.dart:261:10)
I/flutter ( 5730): #17     _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter ( 5730): (elided 3 frames from dart:async)
I/flutter ( 5730): 
I/flutter ( 5730): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Main.dart**

```
home: OfflineBuilder(
                  connectivityBuilder: (
                    BuildContext context,
                    ConnectivityResult connectivity,
                    Widget child,
                  ) {
                    final bool connected =
                        connectivity != ConnectivityResult.none;
                    return Scaffold(
                        body: connected
                            ? Scaffold(
                                body: authProvider.isLogin
                                    ? MainScreen()
                                    : FutureBuilder(
                                        future: authProvider.autoLogin(),
                                        builder: (context, snapshot) =>
                                            snapshot.connectionState ==
                                                    ConnectionState.waiting
                                                ? LogoScreen()
                                                : LoginScreen()))
                            : Center(child: new Text('No internet!')));
                  },
                  child: Center()),
```

**Flutter doctor**

```
Connected views:
wichayut@Wichayuts-MacBook-Pro relifnow_frontend_v2 % flutter doctor -v
[✓] Flutter (Channel master, v1.18.1-pre.9, on Mac OS X 10.15.4 19E266, locale en-TH)
    • Flutter version 1.18.1-pre.9 at /Users/wichayut/Development/flutter
    • Framework revision f9c58bea49 (10 hours ago), 2020-04-04 21:31:55 -0700
    • Engine revision cb6fc30534
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 80ae6ed91d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/wichayut/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (2 available)
    • sdk gphone x86 • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • Dew’s iPhone   • 7a530c8cd5eff84a0e6e0ca0051aa8033e641cfe • ios         • iOS 13.4

• No issues found!
```

**Comment by aadil058** [comment]
`flutter clean`
`flutter run`

**Comment by Ananthan1996** [comment]
Is this running fine in IOS???
